ALTER TABLE users
  ADD COLUMN IF NOT EXISTS display_name VARCHAR(100)  NULL AFTER username,
  ADD COLUMN IF NOT EXISTS bio          TEXT          NULL AFTER display_name,
  ADD COLUMN IF NOT EXISTS phone        VARCHAR(30)   NULL AFTER bio,
  ADD COLUMN IF NOT EXISTS street       VARCHAR(255)  NULL AFTER phone,
  ADD COLUMN IF NOT EXISTS city         VARCHAR(100)  NULL AFTER street,
  ADD COLUMN IF NOT EXISTS state        VARCHAR(100)  NULL AFTER city,
  ADD COLUMN IF NOT EXISTS postal_code  VARCHAR(20)   NULL AFTER state,
  ADD COLUMN IF NOT EXISTS country      VARCHAR(100)  NULL AFTER postal_code,
  ADD COLUMN IF NOT EXISTS skills       JSON          NULL AFTER country;
