INSERT IGNORE INTO `cnf_countries` (`iso2`, `iso3`, `name`, `phone_code`) VALUES
  -- Europa
  ('AD', 'AND', 'Andorra',                        '376'),
  ('AL', 'ALB', 'Albanien',                       '355'),
  ('AT', 'AUT', 'Österreich',                     '43'),
  ('BA', 'BIH', 'Bosnien und Herzegowina',        '387'),
  ('BE', 'BEL', 'Belgien',                        '32'),
  ('BG', 'BGR', 'Bulgarien',                      '359'),
  ('BY', 'BLR', 'Weißrussland',                   '375'),
  ('CH', 'CHE', 'Schweiz',                        '41'),
  ('CY', 'CYP', 'Zypern',                         '357'),
  ('CZ', 'CZE', 'Tschechien',                     '420'),
  ('DE', 'DEU', 'Deutschland',                    '49'),
  ('DK', 'DNK', 'Dänemark',                       '45'),
  ('EE', 'EST', 'Estland',                        '372'),
  ('ES', 'ESP', 'Spanien',                        '34'),
  ('FI', 'FIN', 'Finnland',                       '358'),
  ('FR', 'FRA', 'Frankreich',                     '33'),
  ('GB', 'GBR', 'Vereinigtes Königreich',         '44'),
  ('GR', 'GRC', 'Griechenland',                   '30'),
  ('HR', 'HRV', 'Kroatien',                       '385'),
  ('HU', 'HUN', 'Ungarn',                         '36'),
  ('IE', 'IRL', 'Irland',                         '353'),
  ('IS', 'ISL', 'Island',                         '354'),
  ('IT', 'ITA', 'Italien',                        '39'),
  ('LI', 'LIE', 'Liechtenstein',                  '423'),
  ('LT', 'LTU', 'Litauen',                        '370'),
  ('LU', 'LUX', 'Luxemburg',                      '352'),
  ('LV', 'LVA', 'Lettland',                       '371'),
  ('MC', 'MCO', 'Monaco',                         '377'),
  ('MD', 'MDA', 'Moldau',                         '373'),
  ('ME', 'MNE', 'Montenegro',                     '382'),
  ('MK', 'MKD', 'Nordmazedonien',                 '389'),
  ('MT', 'MLT', 'Malta',                          '356'),
  ('NL', 'NLD', 'Niederlande',                    '31'),
  ('NO', 'NOR', 'Norwegen',                       '47'),
  ('PL', 'POL', 'Polen',                          '48'),
  ('PT', 'PRT', 'Portugal',                       '351'),
  ('RO', 'ROU', 'Rumänien',                       '40'),
  ('RS', 'SRB', 'Serbien',                        '381'),
  ('RU', 'RUS', 'Russland',                       '7'),
  ('SE', 'SWE', 'Schweden',                       '46'),
  ('SI', 'SVN', 'Slowenien',                      '386'),
  ('SK', 'SVK', 'Slowakei',                       '421'),
  ('SM', 'SMR', 'San Marino',                     '378'),
  ('TR', 'TUR', 'Türkei',                         '90'),
  ('UA', 'UKR', 'Ukraine',                        '380'),
  ('VA', 'VAT', 'Vatikanstadt',                   '39'),
  ('XK', 'XKX', 'Kosovo',                         '383'),
  -- Amerika
  ('AG', 'ATG', 'Antigua und Barbuda',            '1268'),
  ('AR', 'ARG', 'Argentinien',                    '54'),
  ('BB', 'BRB', 'Barbados',                       '1246'),
  ('BO', 'BOL', 'Bolivien',                       '591'),
  ('BR', 'BRA', 'Brasilien',                      '55'),
  ('BS', 'BHS', 'Bahamas',                        '1242'),
  ('BZ', 'BLZ', 'Belize',                         '501'),
  ('CA', 'CAN', 'Kanada',                         '1'),
  ('CL', 'CHL', 'Chile',                          '56'),
  ('CO', 'COL', 'Kolumbien',                      '57'),
  ('CR', 'CRI', 'Costa Rica',                     '506'),
  ('CU', 'CUB', 'Kuba',                           '53'),
  ('DO', 'DOM', 'Dominikanische Republik',        '1809'),
  ('EC', 'ECU', 'Ecuador',                        '593'),
  ('GT', 'GTM', 'Guatemala',                      '502'),
  ('GY', 'GUY', 'Guyana',                         '592'),
  ('HN', 'HND', 'Honduras',                       '504'),
  ('HT', 'HTI', 'Haiti',                          '509'),
  ('JM', 'JAM', 'Jamaika',                        '1876'),
  ('MX', 'MEX', 'Mexiko',                         '52'),
  ('NI', 'NIC', 'Nicaragua',                      '505'),
  ('PA', 'PAN', 'Panama',                         '507'),
  ('PE', 'PER', 'Peru',                           '51'),
  ('PR', 'PRI', 'Puerto Rico',                    '1787'),
  ('PY', 'PRY', 'Paraguay',                       '595'),
  ('SR', 'SUR', 'Suriname',                       '597'),
  ('SV', 'SLV', 'El Salvador',                    '503'),
  ('TT', 'TTO', 'Trinidad und Tobago',            '1868'),
  ('US', 'USA', 'Vereinigte Staaten',             '1'),
  ('UY', 'URY', 'Uruguay',                        '598'),
  ('VE', 'VEN', 'Venezuela',                      '58'),
  -- Afrika
  ('AO', 'AGO', 'Angola',                         '244'),
  ('BJ', 'BEN', 'Benin',                          '229'),
  ('BF', 'BFA', 'Burkina Faso',                   '226'),
  ('BI', 'BDI', 'Burundi',                        '257'),
  ('BW', 'BWA', 'Botswana',                       '267'),
  ('CD', 'COD', 'Demokratische Republik Kongo',  '243'),
  ('CF', 'CAF', 'Zentralafrikanische Republik',  '236'),
  ('CG', 'COG', 'Republik Kongo',                '242'),
  ('CI', 'CIV', 'Elfenbeinküste',                '225'),
  ('CM', 'CMR', 'Kamerun',                       '237'),
  ('CV', 'CPV', 'Kap Verde',                     '238'),
  ('DJ', 'DJI', 'Dschibuti',                     '253'),
  ('DZ', 'DZA', 'Algerien',                      '213'),
  ('EG', 'EGY', 'Ägypten',                       '20'),
  ('ER', 'ERI', 'Eritrea',                        '291'),
  ('ET', 'ETH', 'Äthiopien',                     '251'),
  ('GA', 'GAB', 'Gabun',                          '241'),
  ('GH', 'GHA', 'Ghana',                          '233'),
  ('GM', 'GMB', 'Gambia',                         '220'),
  ('GN', 'GIN', 'Guinea',                         '224'),
  ('GQ', 'GNQ', 'Äquatorialguinea',              '240'),
  ('GW', 'GNB', 'Guinea-Bissau',                  '245'),
  ('KE', 'KEN', 'Kenia',                          '254'),
  ('KM', 'COM', 'Komoren',                        '269'),
  ('LR', 'LBR', 'Liberia',                        '231'),
  ('LS', 'LSO', 'Lesotho',                        '266'),
  ('LY', 'LBY', 'Libyen',                         '218'),
  ('MA', 'MAR', 'Marokko',                        '212'),
  ('MG', 'MDG', 'Madagaskar',                     '261'),
  ('ML', 'MLI', 'Mali',                           '223'),
  ('MR', 'MRT', 'Mauretanien',                    '222'),
  ('MU', 'MUS', 'Mauritius',                      '230'),
  ('MW', 'MWI', 'Malawi',                         '265'),
  ('MZ', 'MOZ', 'Mosambik',                       '258'),
  ('NA', 'NAM', 'Namibia',                        '264'),
  ('NE', 'NER', 'Niger',                          '227'),
  ('NG', 'NGA', 'Nigeria',                        '234'),
  ('RW', 'RWA', 'Ruanda',                         '250'),
  ('SC', 'SYC', 'Seychellen',                     '248'),
  ('SD', 'SDN', 'Sudan',                          '249'),
  ('SL', 'SLE', 'Sierra Leone',                   '232'),
  ('SN', 'SEN', 'Senegal',                        '221'),
  ('SO', 'SOM', 'Somalia',                        '252'),
  ('SS', 'SSD', 'Südsudan',                       '211'),
  ('ST', 'STP', 'São Tomé und Príncipe',          '239'),
  ('SZ', 'SWZ', 'Eswatini',                       '268'),
  ('TD', 'TCD', 'Tschad',                         '235'),
  ('TG', 'TGO', 'Togo',                           '228'),
  ('TN', 'TUN', 'Tunesien',                       '216'),
  ('TZ', 'TZA', 'Tansania',                       '255'),
  ('UG', 'UGA', 'Uganda',                         '256'),
  ('ZA', 'ZAF', 'Südafrika',                      '27'),
  ('ZM', 'ZMB', 'Sambia',                         '260'),
  ('ZW', 'ZWE', 'Simbabwe',                       '263'),
  -- Asien & Ozeanien
  ('AE', 'ARE', 'Vereinigte Arabische Emirate',  '971'),
  ('AF', 'AFG', 'Afghanistan',                    '93'),
  ('AM', 'ARM', 'Armenien',                       '374'),
  ('AU', 'AUS', 'Australien',                     '61'),
  ('AZ', 'AZE', 'Aserbaidschan',                  '994'),
  ('BD', 'BGD', 'Bangladesch',                    '880'),
  ('BH', 'BHR', 'Bahrain',                        '973'),
  ('BN', 'BRN', 'Brunei',                         '673'),
  ('BT', 'BTN', 'Bhutan',                         '975'),
  ('CN', 'CHN', 'China',                          '86'),
  ('FJ', 'FJI', 'Fidschi',                        '679'),
  ('GE', 'GEO', 'Georgien',                       '995'),
  ('HK', 'HKG', 'Hongkong',                       '852'),
  ('ID', 'IDN', 'Indonesien',                     '62'),
  ('IL', 'ISR', 'Israel',                         '972'),
  ('IN', 'IND', 'Indien',                         '91'),
  ('IQ', 'IRQ', 'Irak',                           '964'),
  ('IR', 'IRN', 'Iran',                           '98'),
  ('JO', 'JOR', 'Jordanien',                      '962'),
  ('JP', 'JPN', 'Japan',                          '81'),
  ('KG', 'KGZ', 'Kirgisistan',                    '996'),
  ('KH', 'KHM', 'Kambodscha',                     '855'),
  ('KP', 'PRK', 'Nordkorea',                      '850'),
  ('KR', 'KOR', 'Südkorea',                       '82'),
  ('KW', 'KWT', 'Kuwait',                         '965'),
  ('KZ', 'KAZ', 'Kasachstan',                     '7'),
  ('LA', 'LAO', 'Laos',                           '856'),
  ('LB', 'LBN', 'Libanon',                        '961'),
  ('LK', 'LKA', 'Sri Lanka',                      '94'),
  ('MM', 'MMR', 'Myanmar',                        '95'),
  ('MN', 'MNG', 'Mongolei',                       '976'),
  ('MO', 'MAC', 'Macau',                          '853'),
  ('MV', 'MDV', 'Malediven',                      '960'),
  ('MY', 'MYS', 'Malaysia',                       '60'),
  ('NP', 'NPL', 'Nepal',                          '977'),
  ('NZ', 'NZL', 'Neuseeland',                     '64'),
  ('OM', 'OMN', 'Oman',                           '968'),
  ('PG', 'PNG', 'Papua-Neuguinea',                '675'),
  ('PH', 'PHL', 'Philippinen',                    '63'),
  ('PK', 'PAK', 'Pakistan',                       '92'),
  ('PS', 'PSE', 'Palästina',                      '970'),
  ('QA', 'QAT', 'Katar',                          '974'),
  ('SA', 'SAU', 'Saudi-Arabien',                  '966'),
  ('SG', 'SGP', 'Singapur',                       '65'),
  ('SY', 'SYR', 'Syrien',                         '963'),
  ('TH', 'THA', 'Thailand',                       '66'),
  ('TJ', 'TJK', 'Tadschikistan',                  '992'),
  ('TL', 'TLS', 'Osttimor',                       '670'),
  ('TM', 'TKM', 'Turkmenistan',                   '993'),
  ('TW', 'TWN', 'Taiwan',                         '886'),
  ('UZ', 'UZB', 'Usbekistan',                     '998'),
  ('VN', 'VNM', 'Vietnam',                        '84'),
  ('YE', 'YEM', 'Jemen',                          '967');
  
